data_ingestion:
  test_size: 0.25

feature_engineering:
  max_features: 50

model_training:
  clf: logistic_regression
  hyperparameters:
    xgboost:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
    random_forest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42
    logistic_regression:
      penalty: 'l2'
      C: 1.0
    MultinomialNB:
      alpha: 1.0
  